name: Central das Ofertas

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  rodar-ofertas:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install requests

      - name: Executar sistema
        env:
          SHOPEE_APP_ID: ${{ secrets.SHOPEE_APP_ID }}
          SHOPEE_SECRET: ${{ secrets.SHOPEE_SECRET }}
        run: python newfile.py
              
      - name: Salvar ofertas no GitHub 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add ofertas_prontas.txt ofertas_enviadas.json
        git commit -m "Atualizar ofertas" || echo "Nada para atualizar"
        git pull --rebase origin main
        git push origin main
